name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Dependencies
              run: bun install

            - name: Lint
              run: bun run biome:ci

            - name: Run Tests
              run: bun test
